-- ============================================================================
--  KH IL VOSTRO CAFFÈ — استيراد أصناف المنيو إلى القاعدة
--
--  المصدر: index.html (صفحة الرابط) — الأسعار منسوخة حرفيًا.
--  التشغيل: Supabase → SQL Editor → الصق هذا الملف → Run
--  آمن للتشغيل أكثر من مرة (يحدّث بدل التكرار).
--
--  ⚠️ لا أعد تشغيله بعد أن يبدأ المدير بتعديل الأسعار من لوحة الإدارة،
--     وإلا ستُرجع التعديلات إلى قيم المنيو الثابتة.
--
--  الأصناف: 118   ·   التصنيفات: breakfast, coldcoffee, dolci, eveningbox, frappe, hotcoffee, juices, mojito, slush, smoothieshake, tropical
--  الأنواع: سعر مفرد 88 · خيارات/تشكيلات 27 · بوكس 3
--  المعرّفات الجديدة التي يضيفها الإدارة تبدأ من 900000.
-- ============================================================================

begin;

insert into public.menu_items
  (id, ar, it, category, sub, price, price_text, options, image, active)
values
(4, 'نسكافي عادية', 'Nescafé Normale', 'hotcoffee', 'hot_coffee', null, 'يبدأ من 4 د.ل', '[{"label": "صغير", "price": 4.0, "price_text": "4 د.ل"}, {"label": "كبير", "price": 6.0, "price_text": "6 د.ل"}]'::jsonb, 'nescafe.webp', true),
(5, 'قهوه  ايطالية', 'Caffè Latte', 'hotcoffee', 'hot_coffee', 4.0, '4 د.ل', null::jsonb, 'italianc.webp', true),
(6, 'نسكافي كامل', 'Nescafé Completo', 'hotcoffee', 'hot_coffee', null, 'يبدأ من 7 د.ل', '[{"label": "صغير", "price": 7.0, "price_text": "7 د.ل"}, {"label": "كبير", "price": 10.0, "price_text": "10 د.ل"}]'::jsonb, 'fullnescafe.webp', true),
(7, 'كابتيشنو', 'Cappuccino', 'hotcoffee', 'hot_coffee', 5.0, '5 د.ل', null::jsonb, 'capp.webp', true),
(903, 'قهوه عربيه', 'Caffè Arabico', 'hotcoffee', 'hot_coffee', 4.0, '4 د.ل', null::jsonb, 'arabicc.webp', true),
(901, 'شاي احمر مغربي ', 'Tè Rosso Marocchino ', 'hotcoffee', 'hot_tea', 3.0, '3 د.ل', null::jsonb, 'redtea.webp', true),
(902, 'شاي اخضر  مغربي', 'Tè Verde Marocchino ', 'hotcoffee', 'hot_tea', 3.0, '3 د.ل', null::jsonb, 'greentea.webp', true),
(104, 'شاي ماتشا سكر معدل', 'Matcha con zucchero regolato', 'hotcoffee', 'hot_tea', 10.0, '10 د.ل', null::jsonb, 'hotmatcha.webp', true),
(905, 'سحلب باللوز والشامية', 'Sahlab con Mandorle', 'hotcoffee', 'hot_other', 12.0, '12 د.ل', null::jsonb, 'sahlab.webp', true),
(103, 'سحلب عادي', 'Sahlab Normale', 'hotcoffee', 'hot_other', 10.0, '10 د.ل', null::jsonb, 'sahlb1.webp', true),
(906, 'هوت شوكليت', 'Cioccolata Calda', 'hotcoffee', 'hot_other', 15.0, '15 د.ل', null::jsonb, 'hotch.webp', true),
(100, 'اسبريسو', 'Espresso', 'hotcoffee', 'hot_coffee', 4.0, '4 د.ل', null::jsonb, 'esspreso1.webp', true),
(101, 'اسبريسو دبل', 'Espresso Doppio', 'hotcoffee', 'hot_coffee', null, 'يبدأ من 6 د.ل', '[{"label": "بدون ماء", "price": 6.0, "price_text": "6 د.ل"}, {"label": "مع ماء", "price": 7.0, "price_text": "7 د.ل"}]'::jsonb, 'esspreso.webp', true),
(102, 'كافي أمريكانو', 'Caffè Americano', 'hotcoffee', 'hot_coffee', 5.0, '5 د.ل', null::jsonb, 'amreco.webp', true),
(402, 'ماتشا فراولة', 'Matcha alla fragola', 'coldcoffee', 'matcha', 20.0, '20 د.ل', null::jsonb, 'matchastrw.webp', true),
(9000, 'ماتشا مانجو', 'Matcha al mango', 'coldcoffee', 'matcha', 20.0, '20 د.ل', null::jsonb, 'matcham2.webp', true),
(403, 'ماتشا فانيليا', 'Matcha alla vaniglia', 'coldcoffee', 'matcha', 20.0, '20 د.ل', null::jsonb, 'matchav.webp', true),
(405, 'ماتشا بحليب جوز الهند', 'Matcha al latte di cocco', 'coldcoffee', 'matcha', 22.0, '22 د.ل', null::jsonb, 'matcham.webp', true),
(406, 'ماتشا بالحليب', 'Matcha al latte', 'coldcoffee', 'matcha', 19.0, '19 د.ل', null::jsonb, 'matcham.webp', true),
(407, 'ماتشا مركزة', 'Matcha concentrato', 'coldcoffee', 'matcha', 26.0, '26 د.ل', null::jsonb, 'matchass.webp', true),
(911, 'آيس تي توت', 'Tè freddo ai frutti di bosco', 'coldcoffee', 'iced_tea', 12.0, '12 د.ل', null::jsonb, 'iceteablu.webp', true),
(912, 'آيس تي خوخ', 'tè freddo alla pesca', 'coldcoffee', 'iced_tea', 12.0, '12 د.ل', null::jsonb, 'icetea.webp', true),
(913, 'آيس تي لافندر', 'Tè freddo alla lavanda', 'coldcoffee', 'iced_tea', 12.0, '12 د.ل', null::jsonb, 'icetealav.webp', true),
(914, 'آيس تي ليمون ونعناع', 'Tè freddo al limone e menta', 'coldcoffee', 'iced_tea', 12.0, '12 د.ل', null::jsonb, 'icetealem.webp', true),
(915, 'آيس تي باشن فروت', 'Tè freddo al frutto della passione', 'coldcoffee', 'iced_tea', 12.0, '12 د.ل', null::jsonb, 'iceteaba.webp', true),
(9, 'آيس لاتيه', 'Caffè Freddo Italiano', 'coldcoffee', 'iced_coffee', 14.0, '14 د.ل', null::jsonb, 'icedlate.webp', true),
(10, 'آيس بستاشيو لاتيه', 'Caffè Freddo al Pistacchio', 'coldcoffee', 'iced_coffee', 15.0, '15 د.ل', null::jsonb, 'icedpis.webp', true),
(260, 'ايس كافي فانيليا', 'Caffè Vanilla Freddo', 'coldcoffee', 'iced_coffee', 14.0, '14 د.ل', null::jsonb, 'icedcramel.webp', true),
(261, 'ايس كافي فراولة', 'Caffè Fragola Freddo', 'coldcoffee', 'iced_coffee', 14.0, '14 د.ل', null::jsonb, 'iceds.webp', true),
(105, 'ايس كوفي كلاسيك', 'Caffè Freddo Classico', 'coldcoffee', 'iced_coffee', 12.0, '12 د.ل', null::jsonb, 'icecoffecla.webp', true),
(106, 'ايس كوفي كراميل', 'Caffè Freddo al Caramello', 'coldcoffee', 'iced_coffee', 14.0, '14 د.ل', null::jsonb, 'icecoffecra.webp', true),
(11, 'فرابيتشينو', 'Frappuccino', 'coldcoffee', 'iced_coffee', null, 'يبدأ من 12 د.ل', '[{"label": "كلاسيك", "price": 12.0, "price_text": "12 د.ل"}, {"label": "كراميل", "price": 15.0, "price_text": "15 د.ل"}]'::jsonb, 'frapp3.webp', true),
(1, 'عصير مانجو', 'Succo di mango', 'juices', null, null, 'يبدأ من 9 د.ل', '[{"label": "كوب", "price": 9.0, "price_text": "9 د.ل"}, {"label": "لتر", "price": 20.0, "price_text": "20 د.ل"}]'::jsonb, 'mangoj.webp', true),
(73, 'عصير مانجو وفراولة', 'Succo di Mango e Fragola', 'juices', null, null, 'يبدأ من 8 د.ل', '[{"label": "كوب", "price": 8.0, "price_text": "8 د.ل"}]'::jsonb, 'mangos.webp', true),
(32, 'عصير فراولة', 'Succo di Fragola', 'juices', null, null, 'يبدأ من 7 د.ل', '[{"label": "كوب", "price": 7.0, "price_text": "7 د.ل"}, {"label": "لتر", "price": 17.0, "price_text": "17 د.ل"}]'::jsonb, 'strw.webp', true),
(29, 'عصير كوكتيل', 'Succo di Cocktail', 'juices', null, null, 'يبدأ من 10 د.ل', '[{"label": "كوب صغير", "price": 10.0, "price_text": "10 د.ل"}, {"label": "لتر", "price": 22.0, "price_text": "22 د.ل"}]'::jsonb, 'koktail.webp', true),
(72, 'عصير عنب', 'Succo di Uva', 'juices', null, null, 'يبدأ من 10 د.ل', '[{"label": "كوب", "price": 10.0, "price_text": "10 د.ل"}, {"label": "لتر", "price": 28.0, "price_text": "28 د.ل"}]'::jsonb, 'grape.webp', true),
(35, 'عصير برتقال', 'Succo di Arancia', 'juices', null, null, 'يبدأ من 8 د.ل', '[{"label": "كوب", "price": 8.0, "price_text": "8 د.ل"}, {"label": "لتر", "price": 18.0, "price_text": "18 د.ل"}]'::jsonb, 'orange.webp', true),
(2, 'ليمون بالنعناع', 'Limone e Menta', 'juices', null, null, 'يبدأ من 8 د.ل', '[{"label": "كوب", "price": 8.0, "price_text": "8 د.ل"}, {"label": "لتر", "price": 16.0, "price_text": "16 د.ل"}]'::jsonb, 'lemon2.webp', true),
(30, 'فروتا', 'Fruita', 'juices', null, null, 'يبدأ من 12 د.ل', '[{"label": "كوب", "price": 12.0, "price_text": "12 د.ل"}]'::jsonb, 'fruita.webp', true),
(37, 'جوافة وبنجر', 'Guava e Barbabietola', 'juices', null, null, 'يبدأ من 8 د.ل', '[{"label": "كوب", "price": 8.0, "price_text": "8 د.ل"}, {"label": "لتر", "price": 20.0, "price_text": "20 د.ل"}]'::jsonb, 'gwafab.webp', true),
(75, 'عصير جوافة', 'Succo di Guava', 'juices', null, null, 'يبدأ من 8 د.ل', '[{"label": "كوب", "price": 8.0, "price_text": "8 د.ل"}, {"label": "لتر", "price": 18.0, "price_text": "18 د.ل"}]'::jsonb, 'gwafa.webp', true),
(9001, 'عصير أناناس وجوز الهند', 'Succo di ananas e cocco', 'juices', null, null, 'يبدأ من 14 د.ل', '[{"label": "كوب", "price": 14.0, "price_text": "14 د.ل"}]'::jsonb, 'ana.webp', true),
(74, 'عصير اناناس', 'Succo di Ananas', 'juices', null, null, 'يبدأ من 12 د.ل', '[{"label": "كوب", "price": 12.0, "price_text": "12 د.ل"}, {"label": "لتر", "price": 30.0, "price_text": "30 د.ل"}]'::jsonb, 'ana.webp', true),
(602, 'افوكادو', 'Avocado', 'juices', null, 28.0, '28 د.ل', null::jsonb, 'avocado.webp', true),
(108, 'افوكادو دبل', 'Avocado Doppio', 'juices', null, 23.0, '23 د.ل', null::jsonb, 'avocadot.webp', true),
(109, 'افوكادو تربل', 'Avocado Triplo', 'juices', null, 32.0, '32 د.ل', null::jsonb, 'avocadod.webp', true),
(601, 'تروبيكال مانجو', 'Tropical Mango', 'tropical', null, 45.0, '45 د.ل', null::jsonb, 'tro3.webp', true),
(603, 'تروبيكال افوكادو', 'Tropical Avocado', 'tropical', null, 65.0, '65 د.ل', null::jsonb, 'tro2.webp', true),
(604, 'تروبيكال اناناس وجوز الهند', 'Tropical Ananas e Cocco', 'tropical', null, 45.0, '45 د.ل', null::jsonb, 'tro1.webp', true),
(605, 'تروبيكال فراولة', 'Tropical Fragola', 'tropical', null, 49.0, '49 د.ل', null::jsonb, 'trs.webp', true),
(302, 'توت (بلوبيري)', 'Blueberries / Frutti di bosco', 'smoothieshake', null, null, 'يبدأ من 17 د.ل', '[{"label": "كوب", "price": 17.0, "price_text": "17 د.ل"}, {"label": "نصف لتر", "price": 25.0, "price_text": "25 د.ل"}, {"label": "لتر", "price": 35.0, "price_text": "35 د.ل"}]'::jsonb, 'smoothie.webp', true),
(303, 'دولفين', 'Dolphin', 'smoothieshake', null, null, 'يبدأ من 17 د.ل', '[{"label": "كوب", "price": 17.0, "price_text": "17 د.ل"}, {"label": "نصف لتر", "price": 25.0, "price_text": "25 د.ل"}, {"label": "لتر", "price": 35.0, "price_text": "35 د.ل"}]'::jsonb, 'dolphin.webp', true),
(304, 'علكة', 'Gomma', 'smoothieshake', null, null, 'يبدأ من 17 د.ل', '[{"label": "كوب", "price": 17.0, "price_text": "17 د.ل"}, {"label": "نصف لتر", "price": 25.0, "price_text": "25 د.ل"}, {"label": "لتر", "price": 35.0, "price_text": "35 د.ل"}]'::jsonb, 'dolphin.webp', true),
(506, 'بستاشيو', 'Pistacchio', 'smoothieshake', null, null, 'يبدأ من 17 د.ل', '[{"label": "كوب", "price": 17.0, "price_text": "17 د.ل"}, {"label": "نصف لتر", "price": 25.0, "price_text": "25 د.ل"}, {"label": "لتر", "price": 35.0, "price_text": "35 د.ل"}]'::jsonb, 'milkp.webp', true),
(502, 'أوريو', 'Oreo', 'smoothieshake', null, null, 'يبدأ من 17 د.ل', '[{"label": "كوب", "price": 17.0, "price_text": "17 د.ل"}, {"label": "نصف لتر", "price": 25.0, "price_text": "25 د.ل"}, {"label": "لتر", "price": 36.0, "price_text": "36 د.ل"}]'::jsonb, 'milk.webp', true),
(503, 'كندر', 'Kinder', 'smoothieshake', null, null, 'يبدأ من 19 د.ل', '[{"label": "كوب", "price": 19.0, "price_text": "19 د.ل"}, {"label": "نصف لتر", "price": 26.0, "price_text": "26 د.ل"}, {"label": "لتر", "price": 36.0, "price_text": "36 د.ل"}]'::jsonb, 'kn.webp', true),
(504, 'كتكات', 'KitKat', 'smoothieshake', null, null, 'يبدأ من 19 د.ل', '[{"label": "كوب", "price": 19.0, "price_text": "19 د.ل"}, {"label": "نصف لتر", "price": 26.0, "price_text": "26 د.ل"}, {"label": "لتر", "price": 36.0, "price_text": "36 د.ل"}]'::jsonb, 'kitkat.webp', true),
(505, 'باونتي', 'Bounty', 'smoothieshake', null, null, 'يبدأ من 19 د.ل', '[{"label": "كوب", "price": 19.0, "price_text": "19 د.ل"}, {"label": "نصف لتر", "price": 26.0, "price_text": "26 د.ل"}, {"label": "لتر", "price": 36.0, "price_text": "36 د.ل"}]'::jsonb, 'bounty.webp', true),
(507, 'سنكرز', 'Snickers', 'smoothieshake', null, null, 'يبدأ من 19 د.ل', '[{"label": "كوب", "price": 19.0, "price_text": "19 د.ل"}, {"label": "نصف لتر", "price": 26.0, "price_text": "26 د.ل"}, {"label": "لتر", "price": 36.0, "price_text": "36 د.ل"}]'::jsonb, 'snickers.webp', true),
(508, 'مارس', 'Mars', 'smoothieshake', null, null, 'يبدأ من 19 د.ل', '[{"label": "كوب", "price": 19.0, "price_text": "19 د.ل"}, {"label": "نصف لتر", "price": 26.0, "price_text": "26 د.ل"}, {"label": "لتر", "price": 36.0, "price_text": "36 د.ل"}]'::jsonb, 'mars.webp', true),
(509, 'نيوتيلا', 'Nutella', 'smoothieshake', null, null, 'يبدأ من 17 د.ل', '[{"label": "كوب", "price": 17.0, "price_text": "17 د.ل"}, {"label": "نصف لتر", "price": 25.0, "price_text": "25 د.ل"}, {"label": "لتر", "price": 35.0, "price_text": "35 د.ل"}]'::jsonb, 'mn.webp', true),
(9002, 'موخيتو علكة', 'Mojito alla gomma', 'mojito', null, 12.0, '12 د.ل', null::jsonb, 'moje.webp', true),
(9003, 'موخيتو فراولة', 'Mojito alla fragola', 'mojito', null, 12.0, '12 د.ل', null::jsonb, 'mojs.webp', true),
(9004, 'موخيتو ليمون ونعناع', 'Mojito al limone e menta', 'mojito', null, 12.0, '12 د.ل', null::jsonb, 'mojl.webp', true),
(62, 'فربي فراولة', 'Frappé alla fragola', 'frappe', null, 8.0, '8 د.ل', null::jsonb, 'frobys.webp', true),
(63, 'فربي موز', 'Frappé alla banana', 'frappe', null, 8.0, '8 د.ل', null::jsonb, 'fr1.webp', true),
(9005, 'فربي تمر ولوز', 'Frappé di datteri e mandorle', 'frappe', null, 9.0, '9 د.ل', null::jsonb, 'frobytmr.webp', true),
(9006, 'فربي فراولة ومانجا', 'Frappé alla fragola e mango', 'frappe', null, 9.0, '9 د.ل', null::jsonb, 'frobyms.webp', true),
(110, 'فربي مانجا', 'Frappé al mango', 'frappe', null, 8.0, '8 د.ل', null::jsonb, 'frobym.webp', true),
(9007, 'سلاش فواكه', 'Slush di frutta', 'slush', null, 17.0, '17 د.ل', null::jsonb, 'sl2.webp', true),
(9008, 'سلاش مانجو وعلكة 500ml', 'Slush mango e gomma', 'slush', null, 15.0, '15 د.ل', null::jsonb, 'sl1.webp', true),
(111, 'سلاش مانجو وعلكة', 'Slush mango e gomma', 'slush', null, 10.0, '10 د.ل', null::jsonb, 'sl3.webp', true),
(112, 'سلاش مانجو وعلكة وفواكه', 'Slush mango e gomma', 'slush', null, 15.0, '15 د.ل', null::jsonb, 'sl4.webp', true),
(705, 'بوكس افطار ', 'Box Mattino ', 'breakfast', null, null, 'أصنافك المفضلة · بنفس سعر القائمة', null::jsonb, 'box1.webp', true),
(702, 'بوكس افطار ', 'Colazione ', 'breakfast', null, null, 'أصنافك المفضلة · بنفس سعر القائمة', null::jsonb, 'box2.webp', true),
(706, 'بوكس افطار جاهز', 'Box Mattino', 'breakfast', null, 18.0, '18 د.ل', null::jsonb, 'morbox2.webp', true),
(801, 'بوكس مسائي ', 'Box Serale ', 'eveningbox', null, null, 'أصنافك المفضلة · بنفس سعر القائمة', null::jsonb, 'evening3.webp', true),
(50, 'تيراميسو لوتس', 'Tiramisù al loto', 'dolci', 'tiramisu_cakes', 17.0, '17 د.ل', null::jsonb, 'tira2.webp', true),
(59, 'تيراميسو كلاسيك', 'Tiramisù Classico', 'dolci', 'tiramisu_cakes', 15.0, '15 د.ل', null::jsonb, 'tira1.webp', true),
(51, 'تيراميسو بستاشيو', 'Tiramisù al pistacchio', 'dolci', 'tiramisu_cakes', 17.0, '17 د.ل', null::jsonb, 'tira3.webp', true),
(52, 'تيراميسو اوريو', 'Tiramisù all''Oreo', 'dolci', 'tiramisu_cakes', 17.0, '17 د.ل', null::jsonb, 'tira4.webp', true),
(77, 'كيكة مانجو حجم صغير', 'Mango Cake Small', 'dolci', 'tiramisu_cakes', 10.0, '10 د.ل', null::jsonb, 'mangocs.webp', true),
(820, 'ليزي كات كيك حجم صغير', 'Lazy Cat Cake Small', 'dolci', 'tiramisu_cakes', 10.0, '10 د.ل', null::jsonb, 'lazy.webp', true),
(800, 'كيكة لوتس حجم صغير', 'Lotus Cake Small', 'dolci', 'tiramisu_cakes', 12.0, '12 د.ل', null::jsonb, 'luts.webp', true),
(79, 'كيكة بستاشيو', 'Torta al Pistacchio', 'dolci', 'tiramisu_cakes', 12.0, '12 د.ل', null::jsonb, 'pisc.webp', true),
(78, 'كيكة شوكولاته', 'torta al cioccolato', 'dolci', 'tiramisu_cakes', 12.0, '12 د.ل', null::jsonb, 'choc.webp', true),
(66, 'كيكة كندر حجم صغير', 'Kinder Cake Small', 'dolci', 'tiramisu_cakes', 12.0, '12 د.ل', null::jsonb, 'kindercake2.webp', true),
(772, 'كيكة مانجو حجم كبير  جرام', 'Mango Cake Large 750g', 'dolci', 'tiramisu_cakes', 25.0, '25 د.ل', null::jsonb, 'mangoc.webp', true),
(821, 'ليزي كات كيك حجم كبير', 'Lazy Cat Cake Large', 'dolci', 'tiramisu_cakes', 25.0, '25 د.ل', null::jsonb, 'oreoc.webp', true),
(81, 'كيكة كندر حجم كبير', 'Torta Kinder Grande', 'dolci', 'tiramisu_cakes', 30.0, '30 د.ل', null::jsonb, 'kindercake3.webp', true),
(80, 'كيكة لوتس', 'Torta al Lotus', 'dolci', 'tiramisu_cakes', 25.0, '25 د.ل', null::jsonb, 'lutc.webp', true),
(1011, 'بريوش ايطالي', 'Briosh Italiano', 'dolci', 'croissant_briosh', 8.0, '8 د.ل', null::jsonb, 'briosha.webp', true),
(1009, 'بريوش ايطالي مكس ', 'Briosh Misto Pistacchio e Nutella', 'dolci', 'croissant_briosh', 12.0, '12 د.ل', null::jsonb, 'brioshmix.webp', true),
(53, 'بريوش ايطالي محقون', 'Briosh Iniettato', 'dolci', 'croissant_briosh', 10.0, '10 د.ل', null::jsonb, 'briosh2.webp', true),
(1015, 'بريوش فواكه', 'Briosh alla Frutta', 'dolci', 'croissant_briosh', 15.0, '15 د.ل', null::jsonb, 'brioshf.webp', true),
(1019, 'بريوش  نيوتيلا مقصوص', 'Briosh alla Nutella', 'dolci', 'croissant_briosh', 7.0, '7 د.ل', null::jsonb, 'brioshc.webp', true),
(1010, 'بريوش لوتس مقصوص', 'Briosh Lotus', 'dolci', 'croissant_briosh', 10.0, '10 د.ل', null::jsonb, 'l.webp', true),
(1018, 'بريوش  بستاشيو مقصوص', 'Briosh al Pistacchio', 'dolci', 'croissant_briosh', 10.0, '10 د.ل', null::jsonb, 'p.webp', true),
(1016, 'توستر', 'Toast', 'dolci', 'croissant_briosh', 10.0, '10 د.ل', null::jsonb, 'toaster.webp', true),
(1017, 'بيكان', 'Pecan', 'dolci', 'croissant_briosh', 10.0, '10 د.ل', null::jsonb, 'bekan.webp', true),
(1014, 'بريوش شوفان', 'Briosh ai Cereali', 'dolci', 'croissant_briosh', 12.0, '12 د.ل', null::jsonb, 'brioshoat.webp', true),
(1101, 'كريب نيوتيلا ولوز وعسل', 'Crepes Nutella, Mandorle e Miele', 'dolci', 'crepe', 25.0, '25 د.ل', null::jsonb, 'crepenn.webp', true),
(1102, 'كريب مكس', 'Crepes Misto', 'dolci', 'crepe', 30.0, '30 د.ل', null::jsonb, 'crepemix.webp', true),
(1111, 'كريب مكس', 'Crepes Misto', 'dolci', 'crepe', 30.0, '30 د.ل', null::jsonb, 'crepemix2.webp', true),
(1103, 'كريب دبي', 'Crepes Dubai', 'dolci', 'crepe', 32.0, '32 د.ل', null::jsonb, 'crepedu.webp', true),
(1104, 'كريب نيوتيلا', 'Crepes alla Nutella', 'dolci', 'crepe', 19.0, '19 د.ل', null::jsonb, 'crepen.webp', true),
(1105, 'كريب فواكه', 'Crepes alla Frutta', 'dolci', 'crepe', 30.0, '30 د.ل', null::jsonb, 'crepefru.webp', true),
(1107, 'كريب رول نيوتيلا وفستق', 'Crepes Roll Nutella e Pistacchio', 'dolci', 'crepe', 25.0, '25 د.ل', null::jsonb, 'creprollnp.webp', true),
(1108, 'كريب رول فواكه', 'Crepes Roll alla Frutta', 'dolci', 'crepe', 30.0, '30 د.ل', null::jsonb, 'creperollf.webp', true),
(1005, 'بانكيك فستق', 'Pancake al Pistacchio', 'dolci', 'pancake', 20.0, '20 د.ل', null::jsonb, 'pancpis.webp', true),
(1004, 'بانكيك بوتس ونيوتيلا', 'Pancake Lotus e Nutella', 'dolci', 'pancake', 20.0, '20 د.ل', null::jsonb, 'pancakelu.webp', true),
(1007, 'بانكيك بندق ونيوتيلا', 'Pancake Nocciole e Nutella', 'dolci', 'pancake', 20.0, '20 د.ل', null::jsonb, 'pa.webp', true),
(1006, 'بانكيك نيوتيلا', 'Pancake alla Nutella', 'dolci', 'pancake', 19.0, '19 د.ل', null::jsonb, 'panc3.webp', true),
(190, 'بسبوسة قشطة', 'Basbousa con Panna', 'dolci', 'other_sweets', 5.0, '5 د.ل', null::jsonb, 'basbosa2.webp', true),
(122, 'بسبوسة شكلاطة', 'Basbousa al Cioccolato', 'dolci', 'other_sweets', 5.0, '5 د.ل', null::jsonb, 'basbosa.webp', true),
(183, 'دونات', 'Doughnut', 'dolci', 'other_sweets', 10.0, '10 د.ل', null::jsonb, 'donat.webp', true),
(184, 'سينابون', 'Cinnabon', 'dolci', 'other_sweets', 10.0, '10 د.ل', null::jsonb, 'cinnabon.webp', true)
on conflict (id) do update set
  ar         = excluded.ar,
  it         = excluded.it,
  category   = excluded.category,
  sub        = excluded.sub,
  price      = excluded.price,
  price_text = excluded.price_text,
  options    = excluded.options,
  image      = excluded.image,
  updated_at = now();

commit;

-- تحقق سريع بعد التشغيل:
--   select category, count(*) from menu_items group by category order by 1;
--   select count(*) from menu_items;   -- يجب أن تكون 118
